# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
import os
from snakemake.utils import min_version

min_version("6.4.1")


wildcard_constraints:
    sample="[a-zA-Z\d]+",


##### setup report #####
configfile: "config/config.yaml"

##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://condaforge/mambaforge:22.11.1-4"

# report: "report/workflow.rst"

include: "rules/common.smk"
include: "rules/fetchsra.smk"
include: "rules/fastqc.smk"
include: "rules/bamqc.smk"

include: "rules/align.smk"
include: "rules/ref.smk"
include: "rules/callpeak.smk"


##### target rules #####


rule all:
    input:
        get_final_output()