samples: config/samples.csv

tag: 'MOCK'

threads:
  fastp: 12
  star: 12
  homer: 12

reference:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 104
  # Genome build
  build: GRCh38

params:
  macs2: " -f BAM --keep-dup all -g mm --nomodel --extsize 200 -q 0.0001 --fe-cut-off 2  "
  fastp: "-c "
  star: ""
